/**
 * Central Database Schema
 * Auto-generated by drizzle-kit pull and manually refined
 *
 * This schema defines tables in the centralized clinic_db database:
 * - user: Central authentication users
 * - organization: Tenant organizations
 */

import { pgTable, serial, varchar, timestamp, unique, text, boolean } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

/**
 * User table - Central authentication users
 * Each user can create/manage organizations
 */
export const userTable = pgTable("user", {
	id: serial().primaryKey().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }),
	email: varchar({ length: 255 }).notNull(),
	name: varchar({ length: 255 }).notNull(),
	password: varchar({ length: 255 }).notNull(),
	refreshToken: text("refresh_token"),
	isVerified: boolean("is_verified").default(false).notNull(),
}, (table) => {
	return {
		userEmailUnique: unique("user_email_unique").on(table.email),
		userNameUnique: unique("user_name_unique").on(table.name),
	}
});

/**
 * Organization table - Tenant organizations
 * Each organization gets its own distributed database
 */
export const organizationTable = pgTable("organization", {
	id: serial().primaryKey().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'date' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'date' }),
	name: varchar({ length: 255 }).notNull(),
}, (table) => {
	return {
		organizationNameUnique: unique("organization_name_unique").on(table.name),
	}
});
